language: python
python:
  - "3.5"
install:
  - pip install flake8
  - pip install -r requirements.txt
script:
  - flake8 .
  - ./tests.py

notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: never
    urls:
      - https://webhooks.gitter.im/e/20825e759af1c23acbdd
